### ISSUE TITLE
[Feature Request] British English (Gray & Grey)

### ISSUE THREAD

**Issue by panoply** [webdiscus/ansis#1]
**Describe the bug**
Support British English spelling of `gray`. 

**To Reproduce**
Support British english `grey`

**Additional context**
Thank you for work you've done here. This is a brilliant CLI colour variant. Top stuff.

**Comment by webdiscus** [comment]
Hello @panoply,

thanks for reporting the bug.
I know that most libraries use both `gray` and `grey`, but `gray` is more popular. I didn't include `grey` because it's "yet one alias". I want to keep a clean API with no spelling options. This is the reason for the `gray`.

But, you are also right, many developers use the `grey` variant and this alias is needed for compatibility and a quick swith to ansis.

Are you using `grey` spelling variant?

In next version I add the `grey` spelling variant.

**Comment by panoply** [comment]
Hey @webdiscus 

So for me, I have an immediate habit of typing _grey_ . Upon installing TS compiler threw an error. My immediate response was "module has an issue" which of course was not the case. It is totally fine if you don't want to include the variation, just thought you might like to cover that basis. 

Just for some more context, the same logic of `en-GB` spelling occurs quite regularly across the web nexus.  An example is the world `colour` wherein modules will almost always use US English as the standard (spelt `color`) but Europeans are taught British English in schools and also almost all Commonwealth countries use that variation of spelling. For the vast majority of folks `en-GB` spelling is what they will write out of instinct (even after a decade writing code, I still do it). 

Again, thanks for your work with this module. It's wonderful and refreshing.

**Comment by webdiscus** [comment]
Hello @panoply,

thank you for very important details!
The `grey` is now added in version `1.3.3`.
